### ISSUE TITLE
How About add C++ support ?

### ISSUE THREAD

**Issue by sgf** [hhblaze/Biser#2]
How About add C++ support ?

**Comment by hhblaze** [comment]
Feel free to implement it on C++

**Comment by sgf** [comment]
thank you,i know it's hardly to implement in C++.
because  C++ has no reflection.

**Comment by hhblaze** [comment]
Biser doesn't use reflection in its core, that is a point. Help Extension can have reflection, but they are unnecessary.

**Comment by sgf** [comment]
Okay, it is the design of an intrusion
