### ISSUE TITLE
Handle Polymorphism in list?

### ISSUE THREAD

**Issue by robotron2084** [hhblaze/Biser#6]
It seems that I'm unable to have a list such as List<ParentClass> that contains instances of a child class in it.

For example:
```
List<ParentClass>() myList;
ChildClass foo = new ChildClass();
myList.Add(foo);
```
Is it possible to serialize/deserialzie like this?

**Comment by hhblaze** [comment]
Please supply more or less runnable code.

Such constellation works:

```c#
public partial class BC_T1
  {
      public bool Head { get; set; }
  }

  public partial class BC_T2: BC_T1
  {
      public bool Hand { get; set; }
  }

public partial class BC_T3 
{
public List<BC_T2> bcccs { get; set; }
}

----------------------------------   now generate for each class with BiserObjectify encoders and use it like

            //      BiserObjectify.Generator.Run(typeof(BC_T3), true,
            //@"------\VSProjects\tests", forBiserBinary: true, forBiserJson: false, null);

            //      BiserObjectify.Generator.Run(typeof(BC_T1), true,
            //@"---\VSProjects\tests", forBiserBinary: true, forBiserJson: false, null);

            BC_T3 mn1 = new BC_T3 { bcccs = new List<BC_T2>() };

            mn1.bcccs.Add(new BC_T2 { Hand = true, Head = true });            

            var serializedObjectAsByteArray = mn1.BiserEncoder().Encode();
            var retoredBinaryObject = BC_T2.BiserDecode(serializedObjectAsByteArray);

```

**Comment by robotron2084** [comment]
In your example change your list to be of type List<BS_T1> and it will deserialize your BC_T2 as a BC_T1.

**Comment by hhblaze** [comment]
Better if you create for me a sample project

![image](https://user-images.githubusercontent.com/486781/114245904-a6a3ea80-9991-11eb-8e96-5e65c3bf3f0e.png)

**Comment by hhblaze** [comment]
But, there is a non-desired behavior in deserializing, will check if it is possible to fix somehow:

![image](https://user-images.githubusercontent.com/486781/114246111-16b27080-9992-11eb-8c46-1e00698bcc21.png)

![image](https://user-images.githubusercontent.com/486781/114246184-495c6900-9992-11eb-9278-4de0a8ce938f.png)

**Comment by hhblaze** [comment]
And this is hard to fix, because it will use decoder of BC_TC2 (that is richer) to deserialize BC_TC1. 
Must be used like this

![image](https://user-images.githubusercontent.com/486781/114246542-2c746580-9993-11eb-86b8-22cf101d3b2c.png)
